---
title: Project Review Template 
author: Anissa Waller Del Valle 
date: April 30 2026
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: How Medications and Medication Regimens relate to Patient Mortality 

Name of project author(s): Rebecca Basta and Riley Herber 

Name of project reviewer: Anissa Waller Del Valle 


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

1. The context of this project is described well. There is a summary of previous work ("A nationwide cohort study published in Nature..."). It is clear why the project was undertaken. 

2. I can see the references, although they are presented as both (LASTNAME et al., YEAR) and (NUMBER). I would present the references in only one way. 

3. The aims of the project are clear. 

### Summary assessment (PICK ONE, DELETE THE OTHERS)
* strong contextualization and motivation


## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

1. The primary objective of the project is clearly stated. It is clear how the questions relate to the data. 

2. The hypothesis is not explicitly stated. 

### Summary assessment
* question/hypotheses somewhat explained


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

1. The source is provided in **Data Aquisition**. It explicitly states what data were used in this project, and where the data can be located. It is clear what the data is. The data is described well. 

### Summary assessment
* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

1. Data is cleaned/processed and explored well. All steps were reasonable and appropiate for the data and analysis performed. Meaningful exploratory results are shown. 

2. The relative file paths (../../data/...) are a _little_ fragile. Emphasis on little. I had to change my working directory around to run the scripts properly. I wonder if using **here()** would help? 

3. I like the idea of classifying the medication! I am a bit worried about keyword matching, as there is a decent risk of misclassification. Is there an alternative method you could use to ensure that the medications are classified correctly? 

### Summary assessment
* essentially no weaknesses in wrangling and exploratory component



## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

1. The goal of this project is to better understand how medication regiments relate to patient mortality. Only 0.1% of admissions (13 deaths in a 30-day period) resulted in death. This is an incredibly small sample pool. My recommendation would be to look further out (e.g., 90-day mortality) and repeat the analysis, or to **use an approach that is specifically designed to reduce bias in small samples and rare events**. This will help make the odds ratios more stable and tighten your 95% CIs. Incorporating some class weighting (or other related methods) would strengthen your claims. Otherwise, the model is underpowered and unable to accurately predict survival vs. death. 

2. Exposure to medication is incredibly oversimplified (received vs. not received). This does not account for dosage or frequency, which are important factors to consider, leading to substantial bias. 

3. Overall, the analysis pipeline is solid. The data being analyzed is the issue. 

### Summary assessment
* defensible but not optimal analysis 


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

1. The results are presented well. Tables and figures are easy to read and understand. The main figures (**4.2 Full Analysis**) are publication quality. 

2. I would be hesistant to say that Figure 4 displays a non-linear, inverted U-shape. If the x-axis spanned 0 - 100% instead of 0.00% - 0.12%,  this would be a very flat line. 

### Summary assessment
* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

1. Study findings are properly discussed. Strengths and limitations are acknowleged. Findings are interpreted properly, and the low event count (13 deaths) is acknowledged frequently. 

### Summary assessment
* strong, complete and clear discussion


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

1. The project is well structured and in well labled folders (although I am a bit confused at mimic? mimic-processing.qmd and mimic.eda?). There are no junk files. The readme.qmd files associated with each folder contained the appropiate information. I can get an idea of how things fit together. 

### Summary assessment
* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

1. Project is well documented and easy to understand. Enough infrmation was provided, in a combination of both code and as part of the Rmd files. 

### Summary assessment
* fully and well documented



## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

1. Results are fully reproducible. Documentation is provided. I was able to re-run the whole analysis. 

### Summary assessment
* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

1. Alternatives were considered, explored, and discussed. The questions/hypothesis were fully addressed. The study was thorough -- the issue is really the data that were used. 

### Summary assessment
* strong level of thorougness
